### PR TITLE
Overhaul the CHANGELOG.rst file.

### PR DESCRIPTION
**Pull request by Elliria**
* Use imperative mood for all statements.
* Change formatting of some statements.
* Fix syntax for unclosed code insertion.
* Update heading levels to fix GitHub rendering issue (file is now "pretty" on GitHub, links work, and file can now be previewed when editing on GitHub).
* Fix typos.
* Fix grammar.
* Fix punctuation.
* Add missing "New window API method" section.

### CODE REVIEW

**Comment by Elliria** [comment]
This is a major overhaul of the [CHANGELOG.rst](https://github.com/autokey/autokey/blob/master/CHANGELOG.rst) file on the **master** branch. The diff will look a bit frightening, but data wasn't lost. A lot of data was moved around and several changes were made (see pull-request notes above).

See how the file looks after these changes [on my AutoKey fork](https://github.com/Elliria/autokey/blob/master/CHANGELOG.rst).

**Note:** The `CHANGELOG.rst` files on each of the branches are different from one another, so I'm doing each of them separately.

**Comment by josephj11** [comment]
This is really difficult to review. I assume that nothing was lost, but I can't reasonably verify that. I tried printing out both versions, but gave up comparing them almost immediately.

In the future, maybe something like this could be done on the side first in smaller steps so the changes would be easier to verify (even if the final actual PR is all at once like this one is).

A few specific comments:

The first subheading is bug fixes, but an enhancement - exposing Alt-GR is listed.
This should be moved under enhancements.

Under Documentation, the line about README.rst refers to two issues without any summary information. It shouldn't be necessary to look up those two issues to get a general sense of what was done. This is especially true because one of them is qualified with "part of".

General questions (not specific to this PR):

GUI section notes that the application now watches some files and updates itself when it changes. I would like this explored to see exactly what it does and what it doesn't do and what it might take to add this into the Qt front end as well. We should at least open an issue for that even if we can't do it now.

A crash in the Qt macro recorder was fixed. Last I heard, macro recording (which should be renamed to script recording) hasn't worked for years in either front end. I would like a status update on this feature. Even if it works fine, it needs to be checked that it still works fine relative to any new/modified features that are added. it seems like a number of our new features can't be accessed while recording a script. I'm unsure how the whole feature works (if it does work at all).

**Comment by Elliria** [comment]
> This is really difficult to review. I assume that nothing was lost, but I can't reasonably verify that. I tried printing out both versions, but gave up comparing them almost immediately.
> 
> In the future, maybe something like this could be done on the side first in smaller steps so the changes would be easier to verify (even if the final actual PR is all at once like this one is).

Then I'll start over and do it that way so you can get it one small step at a time. It will be many steps.

**Comment by Elliria** [comment]
> The first subheading is bug fixes, but an enhancement - exposing Alt-GR is listed.
This should be moved under enhancements.

It's in the **Bug fix** section in the current [CHANGELOG.rst](https://github.com/autokey/autokey/blob/master/CHANGELOG.rst) file. Deciding whether to put it somewhere else is an issue independent of this pull request that will require investigation. Since I didn't write that entry, I can only recommend that you look through the git history and find the commit that accompanies that CHANGELOG entry and investigate what was done on your own or use git blame to find out who made the change and contact that person to ask about it. You could also do a search through the issue to see if you can find one that mentions something like this.

If you find the issue it references, please let me know so that I can add it to this entry.

**Comment by Elliria** [comment]
> Under Documentation, the line about README.rst refers to two issues without any summary information. It shouldn't be necessary to look up those two issues to get a general sense of what was done. This is especially true because one of them is qualified with "part of".

That is an issue independent of this pull request. Since I wrote that entry, though, I can tell you that it is necessary to look them up, which is exactly why I mentioned them both. CHANGELOG entries are not at all about a general sense, but about specifics.

If you had looked the two issues up, you'd have seen that the changes needed to be done to each branch, so the changes done to **this** branch would only satisfy one third of the changes required to complete the issue, which wanted all three branches to get the change.

Last, but not least, the commit that accompanied that CHANGELOG entry gave the details of exactly what was done. All of that can be found in the git history.

**Comment by Elliria** [comment]
> GUI section notes that the application now watches some files and updates itself when it changes. I would like this explored to see exactly what it does and what it doesn't do and what it might take to add this into the Qt front end as well. We should at least open an issue for that even if we can't do it now.

That is an issue independent of this pull request. Since I didn't write that entry, I can only recommend that you look through the git history and find the commit that accompanies that CHANGELOG entry and investigate what was done on your own or use git blame to find out who made the change and contact that person to ask about it. Also, as you pointed out, if you have a Qt wish, you might want to open a separate issue for it.

**Comment by Elliria** [comment]
> A crash in the Qt macro recorder was fixed. Last I heard, macro recording (which should be renamed to script recording) hasn't worked for years in either front end. I would like a status update on this feature. Even if it works fine, it needs to be checked that it still works fine relative to any new/modified features that are added. it seems like a number of our new features can't be accessed while recording a script. I'm unsure how the whole feature works (if it does work at all).

That is an issue independent of this pull request. Since I didn't write that entry, I can only recommend that you look through the git history and find the commit that accompanies that CHANGELOG entry and investigate what was done on your own or use git blame to find out who made the change and contact that person to ask about it.

**Comment by Elliria** [comment]
Your interest in deep-dives into some of the entries made by the various developers made it clear that investigating those entries could and might involve examination of the git history. That made me realize that the entries will work as search phrases for git investigations if they remain unchanged, but would make such investigations difficult otherwise.

As a result, my new goal for overhauling the CHANGELOG will be done like this:
1. Fix the syntax of the heading levels in the document to fix the GitHub rendering issue, making the document display and behave properly
2. Organize the existing information by alphabetically-sorted categories as needed so that each version's information is in the same place.
3. Convert multi-line entries into one-liners (this will probably involve changing some of the text).
4. Fix the syntax of the one broken code-insertion (this will definitely be a change, but is necessary).

I'm going to close this issue and start over with small changes each time.

**Pull request closed without merging**
